"""Tests for QuarantineStore."""

import os
import sqlite3
import stat
import tempfile
import time
from pathlib import Path

import pytest

from armor.db.migrations import run_migrations
from armor.db.quarantine import QuarantineStore


@pytest.fixture
def temp_db():
    """Create a temporary database with schema."""
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as f:
        db_path = f.name
    run_migrations(db_path)
    yield db_path
    Path(db_path).unlink(missing_ok=True)


@pytest.fixture
def temp_dir():
    """Create a temporary directory for key files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield tmpdir


@pytest.mark.asyncio
async def test_write_encrypts(temp_db, temp_dir):
    """Write encrypts the payload."""
    key_path = os.path.join(temp_dir, ".key")
    store = QuarantineStore(temp_db, key_path=key_path)

    input_text = "sensitive input data"
    quarantine_id = await store.write(input_text)

    assert quarantine_id is not None

    # Get the encrypted data from DB
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT input_text FROM QuarantinedPayload WHERE id = ?", (quarantine_id,))
    row = cursor.fetchone()

    encrypted_text = row[0]

    # Encrypted text should not contain plaintext
    assert input_text not in encrypted_text

    conn.close()


@pytest.mark.asyncio
async def test_decrypt_round_trip(temp_db, temp_dir):
    """Encrypt and decrypt returns original text."""
    key_path = os.path.join(temp_dir, ".key")
    store = QuarantineStore(temp_db, key_path=key_path)

    input_text = "secret data for decryption"
    quarantine_id = await store.write(input_text)

    # Get encrypted text from DB
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT input_text FROM QuarantinedPayload WHERE id = ?", (quarantine_id,))
    row = cursor.fetchone()
    encrypted_text = row[0]
    conn.close()

    # Decrypt
    decrypted = await store.decrypt_payload(encrypted_text)
    assert decrypted == input_text


@pytest.mark.asyncio
async def test_key_autogenerate(temp_db, temp_dir):
    """Key is autogenerated on first write."""
    key_path = os.path.join(temp_dir, ".key")
    assert not Path(key_path).exists()

    store = QuarantineStore(temp_db, key_path=key_path)
    await store.write("test data")

    # Key file should exist
    assert Path(key_path).exists()


@pytest.mark.asyncio
async def test_key_file_mode_0600(temp_db, temp_dir):
    """Key file has mode 0600 (owner read/write only)."""
    key_path = os.path.join(temp_dir, ".key")
    store = QuarantineStore(temp_db, key_path=key_path)

    await store.write("test data")

    # Check file permissions
    file_stat = os.stat(key_path)
    mode = stat.S_IMODE(file_stat.st_mode)

    assert mode == 0o600


@pytest.mark.asyncio
async def test_key_file_world_writable_directory_fails(temp_db):
    """Fails if key directory is world-writable (security check)."""
    # Create a world-writable directory
    import tempfile

    with tempfile.TemporaryDirectory() as world_writable_dir:
        # Make it world-writable
        os.chmod(world_writable_dir, 0o777)

        key_path = os.path.join(world_writable_dir, ".key")
        store = QuarantineStore(temp_db, key_path=key_path)

        # Writing should fail
        with pytest.raises(ValueError, match="world-writable"):
            await store.write("test data")


@pytest.mark.asyncio
async def test_sweep_expired_deletes(temp_db, temp_dir):
    """Sweep deletes expired rows."""
    key_path = os.path.join(temp_dir, ".key")
    # Use -1 hour (1 hour in the past) so it's definitely expired
    store = QuarantineStore(temp_db, key_path=key_path, ttl_hours=-1)

    # Write a row (will be expired)
    quarantine_id = await store.write("test data")
    assert quarantine_id is not None

    # Manually set expires_at to 1 minute ago to ensure expiry
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    expired_time = time.strftime(
        "%Y-%m-%d %H:%M:%S",
        time.localtime(time.time() - 60),
    )
    cursor.execute(
        "UPDATE QuarantinedPayload SET expires_at = ? WHERE id = ?",
        (expired_time, quarantine_id),
    )
    conn.commit()
    conn.close()

    # Sweep
    deleted_count = await store.sweep_expired()

    assert deleted_count >= 1

    # Verify row is gone
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM QuarantinedPayload WHERE id = ?", (quarantine_id,))
    count = cursor.fetchone()[0]

    assert count == 0

    conn.close()


@pytest.mark.asyncio
async def test_sweep_expired_preserves_future(temp_db, temp_dir):
    """Sweep preserves non-expired rows."""
    key_path = os.path.join(temp_dir, ".key")

    # Create store with long TTL
    store = QuarantineStore(temp_db, key_path=key_path, ttl_hours=168)

    # Write one row that will expire
    expired_id = await store.write("expired data")

    # Write another row that will not expire
    future_id = await store.write("future data")

    # Manually set first row to expire 1 minute ago
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    expired_time = time.strftime(
        "%Y-%m-%d %H:%M:%S",
        time.localtime(time.time() - 60),
    )
    cursor.execute(
        "UPDATE QuarantinedPayload SET expires_at = ? WHERE id = ?",
        (expired_time, expired_id),
    )
    conn.commit()
    conn.close()

    # Sweep
    deleted_count = await store.sweep_expired()

    # Should delete at least the expired one
    assert deleted_count >= 1

    # Verify expired is gone
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM QuarantinedPayload WHERE id = ?", (expired_id,))
    count_expired = cursor.fetchone()[0]

    # Verify future is still there
    cursor.execute("SELECT COUNT(*) FROM QuarantinedPayload WHERE id = ?", (future_id,))
    count_future = cursor.fetchone()[0]

    assert count_expired == 0
    assert count_future == 1

    conn.close()
