"""IPC fuzz harness — validates daemon robustness to malformed input.

Tests that the daemon:
- Never crashes on random byte strings or malformed JSON
- Never returns success (decision: pass) on obviously malformed input
- Does not leak file descriptors
- Remains responsive to health checks after fuzzing

This uses hypothesis to generate random inputs. Smoke tests run for ~60s per PR;
a separate nightly workflow runs for ≥1 hour in CI.

Reference: TC-027-04, TC-027-05, TC-027-06
"""

import contextlib
import json
import os
import socket
import subprocess
import tempfile
import time
from collections.abc import Generator
from pathlib import Path

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st


def start_daemon(socket_path: str, db_path: str, timeout: float = 10.0) -> subprocess.Popen:
    """Start the armor daemon as a subprocess.

    Args:
        socket_path: Path to the Unix socket
        db_path: Path to the SQLite database
        timeout: Max time to wait for daemon to start listening

    Returns:
        Popen instance for the daemon process

    Raises:
        TimeoutError: If daemon doesn't start within timeout
    """
    proc = subprocess.Popen(
        ["uv", "run", "armor", "daemon", "--socket", socket_path, "--db", db_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    # Wait for socket to be created
    start_time = time.time()
    while time.time() - start_time < timeout:
        if Path(socket_path).exists():
            time.sleep(0.1)  # Give daemon a moment to bind
            return proc
        time.sleep(0.05)

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()
    raise TimeoutError(f"Daemon failed to start within {timeout}s")


def send_raw(socket_path: str, data: bytes, timeout: float = 2.0) -> bytes:
    """Send raw bytes to the daemon socket and read response.

    Args:
        socket_path: Path to the Unix socket
        data: Raw bytes to send
        timeout: Socket timeout in seconds

    Returns:
        Response bytes (may be empty if connection closed)

    Raises:
        socket.timeout: If response not received within timeout
    """
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.settimeout(timeout)
    try:
        sock.connect(socket_path)
        sock.sendall(data)

        # Try to read response
        response_data = b""
        try:
            while True:
                chunk = sock.recv(4096)
                if not chunk:
                    break
                response_data += chunk
                # Stop after first line (newline-delimited JSON)
                if b"\n" in response_data:
                    break
        except TimeoutError:
            # Timeout reading is OK; may be a slow response
            pass

        return response_data
    finally:
        sock.close()


def get_fd_count() -> int:
    """Get the current process file descriptor count.

    Returns:
        Number of open file descriptors in the calling process
    """
    try:
        return len(os.listdir("/proc/self/fd"))
    except FileNotFoundError:
        # Fallback for non-Linux systems (macOS, etc.)
        return -1


@pytest.fixture
def temp_dir() -> Generator[Path, None, None]:
    """Create and clean up a temporary directory."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def daemon_process(temp_dir: Path) -> Generator[subprocess.Popen, None, None]:
    """Start and stop a daemon process for each test."""
    socket_path = str(temp_dir / "armor.sock")
    db_path = str(temp_dir / "test.db")

    proc = start_daemon(socket_path, db_path)

    yield proc

    # Cleanup
    try:
        proc.terminate()
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()


class TestIPCFuzz:
    """IPC fuzz tests using hypothesis."""

    @given(st.binary(min_size=1, max_size=1024))
    @settings(max_examples=10, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_random_bytes_never_crash(self, random_bytes: bytes) -> None:
        """TC-027-04: Daemon never crashes on random byte input.

        Sends random bytes to the daemon socket. The daemon should:
        - Not crash
        - Return an error response or close the connection gracefully
        - Remain responsive to subsequent health checks

        Args:
            random_bytes: Random byte string generated by hypothesis
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            temp_dir = Path(tmpdir)
            socket_path = str(temp_dir / "armor.sock")
            db_path = str(temp_dir / "test.db")

            # Start daemon fresh for each test
            daemon = start_daemon(socket_path, db_path)

            try:
                # Send random bytes
                response = b""
                with contextlib.suppress(TimeoutError, ConnectionResetError, BrokenPipeError):
                    response = send_raw(socket_path, random_bytes, timeout=1.0)

                # Daemon should still be running
                assert daemon.poll() is None, "Daemon crashed after random bytes"

                # If we got a response, it should be JSON (not a crash dump)
                if response and response.startswith(b"{"):
                    with contextlib.suppress(json.JSONDecodeError, UnicodeDecodeError, ValueError):
                        resp_json = json.loads(response.split(b"\n")[0])
                        # Response should have some basic structure
                        assert isinstance(resp_json, dict)
            finally:
                daemon.terminate()
                try:
                    daemon.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    daemon.kill()
                    daemon.wait()

    @given(st.binary(min_size=1, max_size=1024))
    @settings(max_examples=10, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_malformed_never_succeeds(self, random_bytes: bytes) -> None:
        """TC-027-05: Daemon never returns success on malformed input.

        Sends random/malformed byte strings and verifies:
        - No response has decision: 'pass'
        - Either an error response or connection reset

        Args:
            random_bytes: Random byte string generated by hypothesis
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            temp_dir = Path(tmpdir)
            socket_path = str(temp_dir / "armor.sock")
            db_path = str(temp_dir / "test.db")

            daemon = start_daemon(socket_path, db_path)

            try:
                # Send malformed data
                response = b""
                with contextlib.suppress(TimeoutError, ConnectionResetError, BrokenPipeError):
                    response = send_raw(socket_path, random_bytes, timeout=1.0)

                # If we got a valid JSON response, it should not be a success
                if response and response.startswith(b"{"):
                    with contextlib.suppress(json.JSONDecodeError, ValueError, KeyError):
                        resp_json = json.loads(response.split(b"\n")[0])
                        if "verdict" in resp_json:
                            # Malformed input should not get a 'pass' verdict
                            assert resp_json["verdict"] != "pass", (
                                f"Random bytes received a pass verdict: {random_bytes!r}"
                            )

                assert daemon.poll() is None, "Daemon crashed on malformed input"
            finally:
                daemon.terminate()
                try:
                    daemon.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    daemon.kill()
                    daemon.wait()

    def test_fd_leak_smoke(self, temp_dir: Path) -> None:
        """TC-027-06: Fuzz burst does not leak file descriptors.

        Sends 30 requests in rapid succession and measures the FD count
        before and after. The delta should be small (≤5 for connection churn).

        Args:
            temp_dir: Temporary directory for socket/db
        """
        socket_path = str(temp_dir / "armor.sock")
        db_path = str(temp_dir / "test.db")

        daemon = start_daemon(socket_path, db_path)

        try:
            # Sample FD count before fuzz burst
            fd_count_before = get_fd_count()

            # Send 30 requests (mix of valid and malformed)
            for i in range(30):
                data = b"X" * (i % 256)  # Varying lengths of garbage
                with contextlib.suppress(TimeoutError, ConnectionResetError, BrokenPipeError):
                    send_raw(socket_path, data, timeout=0.5)

            # Allow daemon time to clean up
            time.sleep(0.5)

            # Sample FD count after
            fd_count_after = get_fd_count()

            # On non-Linux, skip this assertion
            if fd_count_before >= 0 and fd_count_after >= 0:
                fd_delta = fd_count_after - fd_count_before
                # Allow small increase for connection pool or internal state
                assert fd_delta <= 5, (
                    f"FD count increased by {fd_delta} (before={fd_count_before}, after={fd_count_after})"
                )

            assert daemon.poll() is None, "Daemon crashed during FD test"
        finally:
            daemon.terminate()
            try:
                daemon.wait(timeout=5)
            except subprocess.TimeoutExpired:
                daemon.kill()
                daemon.wait()

    def test_daemon_responsive_after_fuzz(self, temp_dir: Path) -> None:
        """Daemon remains responsive after receiving random/malformed input.

        Sends 50 malformed requests, then sends a valid request and
        verifies the daemon responds correctly.

        Args:
            temp_dir: Temporary directory for socket/db
        """
        socket_path = str(temp_dir / "armor.sock")
        db_path = str(temp_dir / "test.db")

        daemon = start_daemon(socket_path, db_path)

        try:
            # Fuzz burst
            for i in range(50):
                data = b"\x00" * (1 + (i % 100))
                with contextlib.suppress(TimeoutError, ConnectionResetError, BrokenPipeError):
                    send_raw(socket_path, data, timeout=0.2)

            # Now send a valid request
            valid_request = {
                "v": 1,
                "op": "check.input",
                "payload": {"text": "test after fuzz"},
            }
            response_data = send_raw(socket_path, json.dumps(valid_request).encode() + b"\n")

            # Should get a valid response
            assert response_data, "No response to valid request after fuzz"
            if response_data.startswith(b"{"):
                resp_json = json.loads(response_data.split(b"\n")[0])
                assert "verdict" in resp_json, f"Response missing verdict: {resp_json}"
                assert resp_json["verdict"] in ("pass", "block", "error", "advisory"), (
                    f"Invalid verdict: {resp_json['verdict']}"
                )

            assert daemon.poll() is None, "Daemon died after fuzz burst"
        finally:
            daemon.terminate()
            try:
                daemon.wait(timeout=5)
            except subprocess.TimeoutExpired:
                daemon.kill()
                daemon.wait()
